import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
// import "../assets/globals.scss";
import Header from "@/components/Header/Header";
import TabPanel from "@/components/TabPanel/TabPanel";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Inter({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header></Header>
        <main>


        {children}
        </main>
        <TabPanel></TabPanel>
      </body>
    </html>
  );
}
